### ISSUE TITLE
Force class names on HTML nodes

### ISSUE THREAD

**Issue by eush77** [remarkjs/remark-html#3]
What purpose do generated class names serve, such as `footnotes` on the block containing footnotes or `language-X` on a fenced code block?

The problem is that if a plugin takes advantage of `node.data` to set some specific class names (a code highlighter might want to do that), then it is not obvious how to preserve the “default” class names as well as adding new ones.

For example:

``` js
node.data = node.data || {};
node.data.htmlAttributes = node.data.htmlAttributes || {};
node.data.htmlAttributes.class = ((node.data.htmlAttributes.class || '') + ' important').trim();
```

If two plugins need to add different classes and they are taking this (or similar) approach, then they would succeed (both classes would be set) and hence compose well with each other. However, any other plugin (or external stylesheet) that relies on “default” classes (like `footnotes` or `language-X`) being present on particular HTML tags would fail because applying those plugins would wipe the default class names. And there is no easy way for a plugin to preserve default class names, isn't it?

And as far as I understand, these classes are not (yet) specified, so they are not even part of the API and no plugin can depend on it safely, right?

Maybe a more consistent approach would be either to specify these class names in the docs and not let other plugins wipe them away (i.e. always set these classes during compilation) or abandon completely as not useful.

What do you think?

**Comment by wooorm** [comment]
Thanks for the info and the great question.
Here’s some unrequested background. :smile: I’m currently testing out building [unified](https://github.com/wooorm/unified) for more than just [retext](https://github.com/wooorm/retext) and [mdast](https://github.com/wooorm/mdast); the next one will probably be named `hast`, a “HTML processor powered by plugins”. In addition, in the future (actually pretty close to done), these processor will be able to convert through “bridging”:

``` js
var mdast2hast = require('mdast-to-hast');
var markdown = require('mdast');
var html = require('hast').use('hast-sectionise').use(require('hast-beautify'));

console.log(markdown.bridge(mdast2hast, html).process('# some HTML'));
// '<section>\n  <h1>some HTML</h1>\n</section>'
```

As in, I’d rather like mdast to stay as far away from HTML as possible. That’s its beauty. It can compile to man pages and whatnot else too. Where `hast` will maybe have support for things like `class` as an array, **mdast-html** however should try to be minimal here IMHO.

I’d like to be as simple as possible with mdast-html. The current implementation is simple, but still has useful defaults (e.g., the `language-X` class is suggested by the spec, and the `footnotes` class is used by Kramdown). When a plug-in specifies other classes, they should test and add / remove accordingly. Here it’s similar to how the DOMs `className` works (you have to check if it’s non-empty first before adding, optionally with a space joiner). Note that also a `href` on a link could be overwritten by `node.data.htmlAttributes.href`.

That for opinion and background, the classes set by mdast-html should be seen as defaults rather than basics I think, and plug-ins should try to be as considerate as possible to other plug-ins. However, it’s hard to image what mdast could be used for in the future (for example, I didn’t think of syntax highlighters till this week). Problems need to be faces when they occur.

As a whole, I’m hoping treating classes as defaults (rather than the by you suggested, forced, or omitted) should work. Thoughts?

**Comment by ben-eb** [comment]
It might be nice to expose some basic DOM like methods for mdast-html nodes. Things like `classList`, `getAttribute` etc could be useful. Definitely see the potential for collisions when things like class names are set by the plugin without thought, and an array of classes would be much easier to manage than a class string.

**Comment by eush77** [comment]
@wooorm Moving HTML processing away from mdast makes total sense. :+1: Great to see this ecosystem going forward like this!

> Note that also a href on a link could be overwritten by `node.data.htmlAttributes.href`.

I don't think it is the same because you cannot append to `href`, but only replace completely, and thus there's no default value you could try to preserve.

> When a plug-in specifies other classes, they should test and add / remove accordingly. Here it’s similar to how the DOMs `className` works (you have to check if it’s non-empty first before adding, optionally with a space joiner). […] As a whole, I’m hoping treating classes as defaults […] should work.

You can't check for default classNames in a plugin's transformer, can you? They are [merged in](https://github.com/wooorm/mdast-html/blob/97360a4a1d0e0a1e04b3e3d66ba5b92940ea2715/lib/h.js#L119) during compilation so you as a plugin author are really doomed unless you're doing something like this:

``` js
if (node.type == 'footnoteReference') {
  defaultClass = 'footnote-ref';
}
else if (node.type == 'code') {
  // How crazy is that?
  var FIRST_WORD = /^[^\ \t]+(?=[\ \t]|$)/;
  var language = node.lang && node.lang.match(FIRST_WORD);
  defaultClass = language ? 'language-' + language[0] : '';
}
// ...

node.data.htmlAttributes.class = defaultClass + ' ' + node.data.htmlAttributes.class + ' my-shiny-class';
```

Another option is to add default classNames for all relevant nodes in the mdast-html's transformer rather than in compiler. This way plugins will see them in `node.data`.

**Comment by wooorm** [comment]
@eush77 I’m going for your last option: transformers. I think that that’s the best approach.

@ben-eb I suggest [utilities](https://github.com/wooorm/mdast/blob/master/doc/plugins.md#list-of-utilities) for that instead of cluttering mdast itself with this support. In my opinion most of the tools working with attributes should be separated as plugins for the above mentioned `hast`. The reason for this is because they could also be useful for people who have HTML as input and want to augment their HTML with these tools.

**Comment by ben-eb** [comment]
@wooorm :+1:

**Comment by wooorm** [comment]
@eush77 I opted to not change any others, apart from the code block.
All other’s are either attributes with an interface in mdast (e.g., `"start"` on ordered lists), or from generated HTML (which don’t have an interface in mdast). An example of the latter is the by you mentioned `footnote-ref`, which exists on the HTML `a` inside a HTML `sup` (which maps to the mdast `footnoteReference`).

**Comment by eush77** [comment]
@wooorm Awesome! I definitely overlooked that `footnote-ref` can't be overwritten by a `node.data`, sorry.
