### ISSUE TITLE
Turning images to figure blocks

### ISSUE THREAD

**Issue by calaoa** [remarkjs/remark-html#31]
Hi everyone, 

Unless I'm mistaken, there is no plugin yet for turning image blocks into figure ones, similarly to what the [`markdown-it-implicit-figures`](https://github.com/arve0/markdown-it-implicit-figures) offers in the [markdown-it](https://github.com/markdown-it/markdown-it) context? In case there is none indeed, I'd be ready to implement one. Should anyone have any recommendation of an existing remark plugin to get inspiration from, that would be helpful. Just wondering also if performing the transformation within the HTML rendering process is the best option (`remark-html`), or if creating intermediate markdown containers (e.g. [`remark-containers`](https://github.com/Nevenall/remark-containers) ones) should be favoured.

Cheers and thumbs up,

**Comment by wooorm** [comment]
Hi there!

If you’re going to deal with HTML as tree transforms, then it’s suggested to take the note in the readme serious: use `remark-rehype` first, and create a `rehype` plugin. Plugin ideas can be places in our [`ideas`](https://github.com/rehypejs/ideas) repos. And feel free to ask questions on [Spectrum](https://spectrum.chat/unified?tab=posts). Finally, [`rehype-picture`](https://github.com/rehypejs/rehype-picture) is a plugin that works on images, which you could take inspiration from!

I’ll close this issue here, as there is not something we should change in this project.

Hope this answers your questions, stay safe!

**Comment by calaoa** [comment]
Excellent, thanks a lot @wooorm, I will look into these and will follow up on Spectrum indeed. Cheers!
